plugins:
  - jekyll-relative-links
  - jekyll-sitemap
relative_links:
  enabled: true
  collections: true
include:
  - README.md
#  - index.md
#  - LICENSE.md
#  - COPYING.md
#  - CODE_OF_CONDUCT.md
#  - CONTRIBUTING.md
#  - ISSUE_TEMPLATE.md
#  - PULL_REQUEST_TEMPLATE.md